[package]
name = "media_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.18.1", features = ["v4"] }
anyhow = "1.0.100"
clap = { version = "4.5.45", features = ["derive"] }
clap_derive = { version = "4.0.0-rc.1" }
env_logger = "0.11.8"
ffmpeg-next = { path = "/data/workspace/rust-ffmpeg" }
libc = "0.2.176"
log = "0.4.28"
reqwest = { version = "0.12.23", features = ["stream"] }
tokio = { version = "1.47.1", features = ["full"] }
indicatif = "0.18.0"
futures-util = "0.3.31"
